name: "✨ Feature Request"
description: Suggest a new idea for Plotline
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: "What would you like to see?"
      description: Describe the feature / enhancement
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Why is this useful?"
      description: Explain the usecase for this
    validations:
      required: true
